name: Continuous Integration - Tests

on: [push, pull_request] # Se declenche a chaque push

jobs:
  test-backend:
    runs-on: ubuntu-latest # Runner
    steps:
      - uses: actions/checkout@v3 # Actions
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
        working-directory: ./server
      - name: Run unit tests
        run: npm test
        working-directory: ./server # Execute les tests unitaires
